name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./infra
        run: npm install

      - name: build
        working-directory: ./infra
        run: npm run build

      - name: Deploy
        working-directory: ./infra
        run: cdk deploy --require-approval never
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}